import { catchAsyncErrors } from "../middlewares/catchAsyncErrors.js";
import ErrorHandler from "../middlewares/error.js";
import Project from "../models/projectModel.js";
import { v2 as cloudinary } from "cloudinary";

export const addProject = catchAsyncErrors(async (req, res, next) => {
  try {
  } catch (error) {
    console.log(error);
  }
});

export const updateProject = catchAsyncErrors(async (req, res, next) => {
  try {
  } catch (error) {
    console.log(error);
  }
});

export const deleteProject = catchAsyncErrors(async (req, res, next) => {
  try {
  } catch (error) {
    console.log(error);
  }
});

export const getAllProjects = catchAsyncErrors(async (req, res, next) => {
  try {
  } catch (error) {
    console.log(error);
  }
});

export const getSingleProject = catchAsyncErrors(async (req, res, next) => {
  try {
  } catch (error) {
    console.log(error);
  }
});
